### ISSUE TITLE
uuid format not supported

### ISSUE THREAD

**Issue by agaro1121** [mbryzek/apidoc#621]
Submitting a swagger json with the following causes issues resolving definitions:
```
...
"someField": {
          "type": "string",
           "format": "uuid"
        }
...
```
I believe this is supported in swagger

Also, ApiDoc does not give a specific error for this. The stacktrace looks like the following
```
java.lang.RuntimeException: Failed to resolve definitions: SomeDefinition
	at scala.sys.package$.error(package.scala:27)
	at me.apidoc.swagger.Parser.buildModels(Parser.scala:87)
	at me.apidoc.swagger.Parser.parseDefinitions(Parser.scala:72)
	at me.apidoc.swagger.Parser.parse(Parser.scala:32)
	at me.apidoc.swagger.Parser.parseString(Parser.scala:21)
	at me.apidoc.swagger.SwaggerServiceValidator$$anonfun$1.apply(SwaggerServiceValidator.scala:13)
	at me.apidoc.swagger.SwaggerServiceValidator$$anonfun$1.apply(SwaggerServiceValidator.scala:13)
	at scala.util.Try$.apply(Try.scala:192)
	at me.apidoc.swagger.SwaggerServiceValidator.validate(SwaggerServiceValidator.scala:13)
	at builder.OriginalValidator$WithServiceSpecValidator.validate(OriginalValidator.scala:44)
	at controllers.Versions$$anonfun$putByApplicationKeyAndVersion$1.apply(Versions.scala:158)
	at controllers.Versions$$anonfun$putByApplicationKeyAndVersion$1.apply(Versions.scala:139)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:408)
	at play.api.mvc.ActionBuilder$$anonfun$apply$16.apply(Action.scala:407)
	at controllers.Authenticated$.invokeBlock(AuthenticatedRequest.scala:155)
	at controllers.Authenticated$.invokeBlock(AuthenticatedRequest.scala:143)
	at play.api.mvc.ActionBuilder$$anon$1.apply(Action.scala:493)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
	at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
	at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
	at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$14.apply(Iteratee.scala:537)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by agaro1121** [comment]
Seems to be working now

**Comment by mbryzek** [comment]
odd - thank you for reporting and pls let us know if you see again

**Comment by agaro1121** [comment]
This is working. Thank you for getting back to me. What actually broke here was a format: "epoch" that the iHeartRadio play-swagger library generated. I'm leveraging their work to automate case class definitions. After creating swagger from existing code, I can appreciate creating the documentation first

**Comment by mbryzek** [comment]
thanks!
